//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Secretary.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongregationReport
    {
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    	public CongregationReport()
    	{
    		this.Id = Guid.NewGuid();		
    		this.PublisherReports = new HashSet<PublisherReport>();
    		this.Publishers = new CongrReportPart();
    		this.AuxPioneers = new CongrReportPart();
    		this.Pioneers = new CongrReportPart();
    	}
    
    	public System.Guid Id { get; set; }
    	public Nullable<short> Month { get; set; }
    	public Nullable<short> Year { get; set; }
    	public Nullable<System.DateTime> SendDate { get; set; }
    	public Nullable<short> ActivePublishers { get; set; }
    
    	public CongrReportPart Publishers { get; set; }
    	public CongrReportPart AuxPioneers { get; set; }
    	public CongrReportPart Pioneers { get; set; }
    
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	public virtual ICollection<PublisherReport> PublisherReports { get; set; }
    }
}
