//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Secretary.DbModel
{
    using System;
    
    public partial class CongrReportPart
    {
    	public Nullable<short> NumberOfPublishers { get; set; }
    	public Nullable<short> Hours { get; set; }
    	public short Returns { get; set; }
    	public Nullable<short> Studies { get; set; }
    }
}
