//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Secretary.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publisher
    {
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    	public Publisher()
    	{
    		this.Id = Guid.NewGuid();		
    		this.PublisherReports = new HashSet<PublisherReport>();
    	}
    
    	public System.Guid Id { get; set; }
    	public string FirstName { get; set; }
    	public string SecondName { get; set; }
    	public string PatronymicName { get; set; }
    	public Nullable<System.DateTime> BirhtDade { get; set; }
    	public Nullable<System.DateTime> BaptizeDate { get; set; }
    	public Hope Hope { get; set; }
    	public string Address { get; set; }
    	public string FixedPhone { get; set; }
    	public string MobilePhone { get; set; }
    	public Nullable<bool> IsElder { get; set; }
    	public Nullable<bool> IsServant { get; set; }
    	public Nullable<bool> IsPioneer { get; set; }
    	public Nullable<bool> IsActive { get; set; }
    	public Nullable<bool> IsRegular { get; set; }
    
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	public virtual ICollection<PublisherReport> PublisherReports { get; set; }
    }
}
