//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Secretary.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublisherReport
    {
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    	public PublisherReport()
    	{
    		this.Id = Guid.NewGuid();		
    	}
    
    	public System.Guid Id { get; set; }
    	public Nullable<short> Month { get; set; }
    	public Nullable<short> Year { get; set; }
    	public Nullable<short> Publications { get; set; }
    	public Nullable<short> VideoPresentations { get; set; }
    	public short Hours { get; set; }
    	public Nullable<short> Returns { get; set; }
    	public Nullable<short> Studies { get; set; }
    	public string Notes { get; set; }
    	public System.Guid PublisherId { get; set; }
    	public Nullable<System.Guid> CongrReportId { get; set; }
    
    	public virtual CongregationReport CongregationReport { get; set; }
    	public virtual Publisher Publisher { get; set; }
    }
}
