//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Secretary.DbModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SecretaryDBContext : DbContext
    {
        public SecretaryDBContext()
            : base("name=SecretaryDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CongregationReport> CongregationReports { get; set; }
        public virtual DbSet<PublisherReport> PublisherReports { get; set; }
        public virtual DbSet<Publisher> Publishers { get; set; }
    }
}
